<?php defined('BASEPATH') OR exit('No direct script access allowed');

//PERMISOS
defined('ID_PERMISO_EVENTO')     OR define('ID_PERMISO_EVENTO', 71);
defined('ID_PERMISO_CONTACTOS')  OR define('ID_PERMISO_CONTACTOS', 73);
defined('ID_PERMISO_EVALUACION') OR define('ID_PERMISO_EVALUACION', 74);
defined('ID_PERMISO_CONFIG_EVAL')  OR define('ID_PERMISO_CONFIG_EVAL', 82);
defined('ID_PERMISO_TURNOS')     OR define('ID_PERMISO_TURNOS', 88);

//OPCION USUARIO
defined('OPCION_ASISTIRA')    OR define('OPCION_ASISTIRA', 1);
defined('OPCION_TALVEZ')      OR define('OPCION_TALVEZ', 2);
defined('OPCION_NO_ASISTIRA') OR define('OPCION_NO_ASISTIRA', 3);

//COMBOS

//TIPO EVENTOS
defined('TIPO_EVENTO_TOUR')              OR define('TIPO_EVENTO_TOUR', 1);
defined('TIPO_EVENTO_CHARLA')            OR define('TIPO_EVENTO_CHARLA', 4);
defined('TIPO_EVENTO_EVALUACION')        OR define('TIPO_EVENTO_EVALUACION', 2);
defined('TIPO_EVENTO_EVALUACION_VERANO') OR define('TIPO_EVENTO_EVALUACION_VERANO', 3);
defined('TIPO_EVENTO_EVALUACION_SEDE')   OR define('TIPO_EVENTO_EVALUACION_SEDE', 5);

//ESTADO EVENTOS
defined('EVENTO_PENDIENTE') OR define('EVENTO_PENDIENTE', "PENDIENTE");
defined('EVENTO_REALIZADO') OR define('EVENTO_REALIZADO', "FINALIZADO");
defined('EVENTO_ANULADO') OR define('EVENTO_ANULADO', "ANULADO");

//COMBO TIPO
defined('COMBO_TIPO_EVENTO')            OR define('COMBO_TIPO_EVENTO', 40);
defined('COMBO_SEGUIMIENTO')            OR define('COMBO_SEGUIMIENTO', 41);
defined('COMBO_RECURSOS_MATERIALES')    OR define('COMBO_RECURSOS_MATERIALES', 42);
defined('COMBO_TIPO_OPCION_ASISTENCIA') OR define('COMBO_TIPO_OPCION_ASISTENCIA', 43);
defined('COMBO_MEDIO_COLEGIO')          OR define('COMBO_MEDIO_COLEGIO', 44);
defined('COMBO_OPERADOR_TELEF')         OR define('COMBO_OPERADOR_TELEF', 45);
defined('COMBO_CANAL_COMUNICACION')     OR define('COMBO_CANAL_COMUNICACION', 46);
defined('COMBO_RESULTADO_DIAGNOSTICO')  OR define('COMBO_RESULTADO_DIAGNOSTICO', 48);

//ASISTENCIA CONTACTO
defined('ASISTENCIA_CONTACTO')   OR define('ASISTENCIA_CONTACTO', 1);
defined('INASISTENCIA_CONTACTO') OR define('INASISTENCIA_CONTACTO', 0);

//ASISTENCIA APOYO ADMINISTRATIVO
defined('ASISTENCIA_APOYO_ADM')   OR define('ASISTENCIA_APOYO_ADM', 1);
defined('INASISTENCIA_APOYO_ADM') OR define('INASISTENCIA_APOYO_ADM', 0);

defined('ASISTENCIA_DIRECTA_CONTACTO')    OR define('ASISTENCIA_DIRECTA_CONTACTO', 1);
defined('ASISTENCIA_INVITACION_CONTACTO') OR define('ASISTENCIA_INVITACION_CONTACTO', 0);

//NUMERO FAMILIAS CARGA
defined('NUMERO_FAMILIAS_CARGA') OR define('NUMERO_FAMILIAS_CARGA',10);


//ESTADO CONTACTO
defined('ESTADO_CONTACTO_CONTACTADO')         OR define('ESTADO_CONTACTO_CONTACTADO',1);
defined('ESTADO_CONTACTO_POR_CONTACTAR')      OR define('ESTADO_CONTACTO_POR_CONTACTAR',2);
defined('ESTADO_CONTACTO_TOUR')               OR define('ESTADO_CONTACTO_TOUR',3);
defined('ESTADO_CONTACTO_EVALUADO_PROCESO')   OR define('ESTADO_CONTACTO_EVALUADO_PROCESO',4);
defined('ESTADO_CONTACTO_EVALUADO_APTO')      OR define('ESTADO_CONTACTO_EVALUADO_APTO',5);
defined('ESTADO_CONTACTO_EVALUADO_NO_APTO')   OR define('ESTADO_CONTACTO_EVALUADO_NO_APTO',6);
defined('ESTADO_CONTACTO_PAGO_CUOTA_INGRESO') OR define('ESTADO_CONTACTO_PAGO_CUOTA_INGRESO',7);
defined('ESTADO_CONTACTO_PAGO_MATRICULA')     OR define('ESTADO_CONTACTO_PAGO_MATRICULA',8);
defined('ESTADO_CONTACTO_MATRICULADO')        OR define('ESTADO_CONTACTO_MATRICULADO',9);
defined('ESTADO_CONTACTO_VERANO')             OR define('ESTADO_CONTACTO_VERANO',10);

defined('FLG_TOMA_ASISTENCIA') OR define('FLG_TOMA_ASISTENCIA', 1);

//TIPO DE RECURSOS
defined('TIPO_RECURSO_MATERIAL') OR define('TIPO_RECURSO_MATERIAL', 1);
defined('TIPO_RECURSO_HUMANO') OR define('TIPO_RECURSO_HUMANO', 2);
defined('TIPO_RECURSO_FICTISIO') OR define('TIPO_RECURSO_FICTISIO', 3);

//FLAG APODERADO
defined('FLG_APODERADO') OR define('FLG_APODERADO', 1);

//FLG DEL EVENTO
defined('ACCION_DETALLE_EVENTO_EDITAR') OR define('ACCION_DETALLE_EVENTO_EDITAR', 1);
defined('ACCION_DETALLE_EVENTO_VER') OR define('ACCION_DETALLE_EVENTO_VER', 0);

//SEDE POR DEFINIR
defined('SEDE_POR_DEFINIR') OR define('SEDE_POR_DEFINIR', 0);

//CANAL DE COMUNICACIÓN
defined('CANAL_PAGINA_WEB') OR define('CANAL_PAGINA_WEB', 4);

//ARRAY ROLES 
define("ROLES_PRIORIZAR_EVENTOS", json_encode(array (ID_ROL_MARKETING, ID_ROL_SUBDIRECTOR)));

//FLG CAMPOS OBLIGATORIOS
defined('CAMPOS_OBLIGATORIOS_COMPLETOS')   OR define('CAMPOS_OBLIGATORIOS_COMPLETOS', 1);
defined('CAMPOS_OBLIGATORIOS_INCOMPLETOS') OR define('CAMPOS_OBLIGATORIOS_INCOMPLETOS', 0);

//FLG_CONFIRMACION
defined('FLG_CONFIRMACION_AUXILIAR') OR define('FLG_CONFIRMACION_AUXILIAR', 1);
defined('FLG_NO_CONFIRMACION_AUXILIAR') OR define('FLG_NO_CONFIRMACION_AUXILIAR', 0);

//ESTADO EVALUACION
defined('EVALUACION_A_EVALUAR')    OR define('EVALUACION_A_EVALUAR', 1);
defined('EVALUACION_EVALUADO')     OR define('EVALUACION_EVALUADO', 2);
defined('EVALUACION_ENTREVISTADO') OR define('EVALUACION_ENTREVISTADO', 3);
defined('EVALUACION_MATRICULA')    OR define('EVALUACION_MATRICULA', 4);
defined('EVALUACION_CANCELADA')    OR define('EVALUACION_CANCELADA', 5);

//FORMULARIO COMPLETO
defined('FLG_FORMULARIO_COMPLETO') OR define('FLG_FORMULARIO_COMPLETO',1);

//TIPOS DE DIAGNOSTICOS
defined('DIAGNOSTICO_CURSO')   OR define('DIAGNOSTICO_CURSO'  ,1);
defined('DIAGNOSTICO_ENTREVISTA')   OR define('DIAGNOSTICO_ENTREVISTA'  ,2);

//FLG_DIAGNOSTICO_APTO
defined('DIAGNOSTICO_APTO')      OR define('DIAGNOSTICO_APTO'  ,1);
defined('DIAGNOSTICO_NO_APTO')   OR define('DIAGNOSTICO_NO_APTO'  ,2);

//SEDES
defined('SEDE_INICIAL_KIDS')   OR define('SEDE_INICIAL_KIDS'  ,4);

defined('RUTA_IMAGENES_ADMISION')   OR define('RUTA_IMAGENES_ADMISION', 'http://'.(isset($_SERVER['HTTP_HOST']) ? $_SERVER['HTTP_HOST'] : null).'/smiledu/uploads/modulos/admision/imagenes/');
defined('RUTA_DOCUMENTOS_ADMISION') OR define('RUTA_DOCUMENTOS_ADMISION', 'http://'.(isset($_SERVER['HTTP_HOST']) ? $_SERVER['HTTP_HOST'] : null).'/smiledu/uploads/modulos/admision/documentos/');

//POSTULANTE
defined('POSTULANTE')   OR define('POSTULANTE'  ,'POSTULANTE');

//ESTADO_EVALUACION_ENTREVISTA
defined('ESTADO_SU_TURNO_CONTACTO')     OR define('ESTADO_SU_TURNO_CONTACTO' , 'SU_TURNO');
defined('ESTADO_PERDIO_TURNO_CONTACTO') OR define('ESTADO_PERDIO_TURNO_CONTACTO', 'PERDIO_TURNO');
defined('ESTADO_EN_ENTREVISTA')         OR define('ESTADO_EN_ENTREVISTA', 'EN_ENTREVISTA');
defined('ESTADO_ENTREVISTADO')          OR define('ESTADO_ENTREVISTADO', 'ENTREVISTADO');
defined('ESTADO_CANCELADA')             OR define('ESTADO_CANCELADA', 'CANCELADA');

//TIPO PREGUNTAS 
defined('PREGUNTA_SINO')    OR define('PREGUNTA_SINO'  ,'SINO');
defined('PREGUNTA_LIBRE')   OR define('PREGUNTA_LIBRE'  ,'OPCIONLIBRE');
defined('PREGUNTA_1OPCION') OR define('PREGUNTA_1OPCION'  ,'1OPCION');
defined('PREGUNTA_NOPCION') OR define('PREGUNTA_NOPCION'  ,'NOPCION');