<?php defined('BASEPATH') OR exit('No direct script access allowed');

//PERMISOS
defined('ID_PERMISO_COLABORADORES')         OR define('ID_PERMISO_COLABORADORES', 75);
defined('ID_PERMISO_INCIDENCIAS')           OR define('ID_PERMISO_INCIDENCIAS', 76);
defined('ID_PERMISO_CAPACITACIONES')        OR define('ID_PERMISO_CAPACITACIONES', 77);
defined('ID_PERMISO_SOLICITUDES_PERSONAL')  OR define('ID_PERMISO_SOLICITUDES_PERSONAL', 78);
defined('ID_PERMISO_CERT_INGLES_DOCENTES')  OR define('ID_PERMISO_CERT_INGLES_DOCENTES', 79);


defined('NUMERO_COLABORADORES_CARGA')  OR define('NUMERO_COLABORADORES_CARGA', 10);